### ISSUE TITLE
Kerberos Dependency update for CentOS / RH

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#10]
When I updated my CentOS, I have found out that a Kerberos dependency has evolved and is no longer available for OpenLDAP contrib overlays.

> Erreur : Paquet : openldap-ltb-contrib-overlays-2.4.44-2.el7.x86_64 (ltb-project)
>              Requiert : libkadm5srv_mit.so.9()(64bit)

Indeed, in CentOS 7,2 I had:

```
[root@localhost /]# rpm -qla krb5-libs | grep -E '.*so.*'
/usr/lib64/krb5/plugins/kdb/db2.so
/usr/lib64/krb5/plugins/tls/k5tls.so
/usr/lib64/libgssapi_krb5.so.2
/usr/lib64/libgssapi_krb5.so.2.2
/usr/lib64/libgssrpc.so.4
/usr/lib64/libgssrpc.so.4.2
/usr/lib64/libk5crypto.so.3
/usr/lib64/libk5crypto.so.3.1
/usr/lib64/libkadm5clnt_mit.so.8
/usr/lib64/libkadm5clnt_mit.so.8.0
/usr/lib64/libkadm5srv_mit.so.9
/usr/lib64/libkadm5srv_mit.so.9.0
/usr/lib64/libkdb5.so.8
/usr/lib64/libkdb5.so.8.0
/usr/lib64/libkrad.so.0
/usr/lib64/libkrad.so.0.0
/usr/lib64/libkrb5.so.3
/usr/lib64/libkrb5.so.3.3
/usr/lib64/libkrb5support.so.0
/usr/lib64/libkrb5support.so.0.1
```

Whereas in CentOS 7.3:

```
[root@localhost yum.repos.d]# rpm -qla krb5-libs | grep -E '.*so.*'
/usr/lib64/krb5/plugins/tls/k5tls.so
/usr/lib64/libgssapi_krb5.so.2
/usr/lib64/libgssapi_krb5.so.2.2
/usr/lib64/libgssrpc.so.4
/usr/lib64/libgssrpc.so.4.2
/usr/lib64/libk5crypto.so.3
/usr/lib64/libk5crypto.so.3.1
/usr/lib64/libkdb5.so.8
/usr/lib64/libkdb5.so.8.0
/usr/lib64/libkrad.so.0
/usr/lib64/libkrad.so.0.0
/usr/lib64/libkrb5.so.3
/usr/lib64/libkrb5.so.3.3
/usr/lib64/libkrb5support.so.0
/usr/lib64/libkrb5support.so.0.1
```

**Comment by coudot** [comment]
Seems we need libkadm5 package on CentOS 7.3 : https://centos.pkgs.org/7/centos-updates-x86_64/libkadm5-1.14.1-27.el7_3.x86_64.rpm.html

But this provides libkadm5srv_mit.so.10.0, so may need to recompile LTB packages. You can try a symlink from 9 to 10 version, it may work if new version does not break compatibility.

**Comment by davidcoutadeur** [comment]
I don't really need it for now... I just reported the bug for next OpenLDAP release

**Comment by coudot** [comment]
I just had this issue today. It prevents to install contrib-overlays package on RHEL 7. I plan to release 2.4.44-3 to fix this. As we have already done a lot of changes for 2.4.45, these packages will have it too.
