### ISSUE TITLE
overlay auditlog doesn't write log

### ISSUE THREAD

**Issue by grosminet57** [ltb-project/openldap-rpm#103]
Hello,

I'd like want add the overlay auditlog to the backend mdb.
to do this:

first , i've created the destination directory and ouput log file.

ll -al /tmp/slapd/auditlog.ldif
-rwxrwxrwx 1 ldap ldap 0 12 janv. 10:51 /tmp/slapd/auditlog.ldif
[root@server01 slapd]# ll -al /tmp/slapd
total 4
drwxrwxrwx   2 ldap ldap   27 12 janv. 10:57 .
drwxrwxrwt. 16 root root 4096 12 janv. 14:52 ..
-rwxrwxrwx   1 ldap ldap    0 12 janv. 10:51 auditlog.ldif

I 've setted extended rights for test only

then, I've loaded module:

**file:**

cat /tmp/module.ldif
dn: cn=module{0},cn=config
changetype: modify
add: olcModuleLoad
olcModuleLoad: auditlog.la

**command:**

ldapmodify -x -a -H ldap://localhost:10400 -D cn=config -W -f /tmp/module.ldif

**result:**

dn: cn=module{0},cn=config
objectClass: olcModuleList
cn: module{0}
olcModulePath: /usr/local/openldap/libexec/openldap
olcModuleLoad: {0}back_mdb.la
olcModuleLoad: {1}ppolicy.la
olcModuleLoad: {2}auditlog.la
structuralObjectClass: olcModuleList
entryUUID: 5c6e85d4-2541-103d-8cc5-4f77754bbcbc
creatorsName: cn=config
createTimestamp: 20230110144650Z
entryCSN: 20230112100330.163016Z#000000#000#000000

Then, I've added this overlay to the backend mdb

**file:**

cat /tmp/auditlog.ldif
dn: olcOverlay=auditlog,olcDatabase={1}mdb,cn=config
changetype: add
objectClass: olcOverlayConfig
objectClass: olcAuditLogConfig
olcOverlay: auditlog
olcAuditlogFile: /tmp/slapd/auditlog.ldif

**command:**

ldapmodify -x -a -H ldap://localhost:10400 -D cn=config -W -f /tmp/auditlog.ldif

**result:**

dn: olcOverlay={0}auditlog,olcDatabase={1}mdb,cn=config
objectClass: olcOverlayConfig
objectClass: olcAuditlogConfig
olcOverlay: {0}auditlog
olcAuditlogFile: /tmp/slapd/auditlog.ldif
structuralObjectClass: olcAuditlogConfig
entryUUID: 82903610-26ac-103d-9760-17a7fb6d0f86
creatorsName: cn=config
createTimestamp: 20230112100622Z
entryCSN: 20230112100622.106922Z#000000#000#000000
modifiersName: cn=config
modifyTimestamp: 20230112100622Z

The files needed for the overlay:

ll /usr/local/openldap/libexec/openldap | grep auditlog
lrwxrwxrwx 1 root root     21 19 août  17:59 auditlog-2.5.so.0 -> auditlog-2.5.so.0.1.8
-rwxr-xr-x 1 root root  11696 19 août  17:59 auditlog-2.5.so.0.1.8
-rw-r--r-- 1 root root   1071 19 août  17:59 auditlog.la
lrwxrwxrwx 1 root root     21 19 août  17:59 auditlog.so -> auditlog-2.5.so.0.1.8

[root@server01 slapd]# locate auditlog-2.5.so.0
/usr/local/openldap/libexec/openldap/auditlog-2.5.so.0
/usr/local/openldap/libexec/openldap/auditlog-2.5.so.0.1.8
[root@server01 slapd]# locate auditlog.so
/usr/local/openldap/libexec/openldap/auditlog.so
[root@server01 slapd]# locate libldap.la
/usr/local/openldap/lib64/libldap.la
[root@server01 slapd]# locate liblber.la
/usr/local/openldap/lib64/liblber.la

Then, I've restarted slapd.

slapd-cli restart
slapd-cli: [INFO] Using /usr/local/openldap/etc/openldap/slapd-cli.conf for configuration
slapd-cli: [INFO] Launching OpenLDAP configuration test...
slapd-cli: [OK] OpenLDAP configuration test successful
slapd-cli: [INFO] Halting OpenLDAP...
slapd-cli: [OK] OpenLDAP stopped
slapd-cli: [INFO] No data backup done
slapd-cli: [INFO] Launching OpenLDAP...
slapd-cli: [OK] File descriptor limit set to 65536
slapd-cli: [OK] OpenLDAP started

**The Problem:**

ldapsearch -x -b "ou=Personne,o=xxx,dc=xxx-yyy,dc=fr" -H ldap://server01:10400 -D "cn=test,ou=Personne,o=xxx,dc=xxx-yyy,dc=fr" -W
Enter LDAP Password:
ldap_bind: Invalid credentials (49)

tail /var/log/slapd/slapd.log

Jan 12 15:07:33 server01 slapd[70892]: conn=1000 fd=13 ACCEPT from IP=192.168.102.67:53886 (IP=0.0.0.0:10400)
Jan 12 15:07:33 server01 slapd[70892]: conn=1000 op=0 BIND dn="cn=test,ou=Personne,o=xxx,dc=xxx-yyy,dc=fr" method=128
Jan 12 15:07:33 server01 slapd[70892]: conn=1000 op=0 RESULT tag=97 err=49 qtime=0.000014 etime=0.000738 text=
Jan 12 15:07:33 server01 slapd[70892]: conn=1000 op=1 UNBIND
Jan 12 15:07:33 server01 slapd[70892]: conn=1000 fd=13 closed

tail /tmp/slapd/auditlog.ldif
ll -al /tmp/slapd/auditlog.ldif
-rwxrwxrwx 1 ldap ldap 0 12 janv. 10:51 /tmp/slapd/auditlog.ldif

My destination file for auditlog stay empty.

Could you help me please ?

**Comment by davidcoutadeur** [comment]
Please don't ask questions in the issues. Use rather the mailing lists

As defined in the man page, the Audit logging overlay only logs write operations. Bad authentication or LDAP search are not write operations.
```
The  Audit  Logging  overlay can be used to record all changes on a given backend database to a specified log file.
```
