### ISSUE TITLE
gpg signature in 2.6.5 RPM for RHEL 9/x86_64 is broken

### ISSUE THREAD

**Issue by kkeane** [ltb-project/openldap-rpm#108]
A few months ago, I successfully installed 2.6.4. I confirmed that I still have the same GPG key, but trying to install 2.6.5 results in:

The GPG keys listed for the "LTB project OpenLDAP 2.6 RHEL 9" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: openldap-ltb-2.6.5-1.el9.x86_64
GPG Keys are configured as: <redacted>
Error: GPG check FAILED

I double-checked that the GPG key I'm using (from our Foreman server) matches the one in https://ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-project

**Comment by coudot** [comment]
Hello @kkeane 

I just published RPMs for OpenLDAP 2.6.6, the signature should be ok now.

**Comment by kkeane** [comment]
You appear to be right. I can't exactly reproduce your steps because importing the key would mess up my DNF configuration, but something must have changed on my end; even 2.6.4 now fails validation even though it successfully installed a few weeks ago.

2.6.6 also fails validation, of course, but not due to what you are doing.

Sorry for sending you on a wild goose chase!

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by kwizart** [comment]
@coudot 
The signature is using the DSA/SHA1, both are wrong for RHEL9 defaults. 
- SHA1 older hash algo is dis-allowed by default for RHEL9 as used in signature.
- Pretty sure that DSA is also dis-allowed, so this needs a newer (RSA 2048 or better) key.

See also https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

The security level could eventually be modified by using LEGACY in crypto policy. But At this point I do not recommend for such older DSA signature and hash algo.

Also  it is safe to use SHA-256 for anything still maintained (EL7->EL9). So my recommendation is to generate a newer GPG key  (RSA 2048) and use that to re-sign the whole repositories (even debian I would say) with the newer key. Eventually starting first with EL9 to verify...


```
$ rpm -qpi openldap-ltb-2.6.6-1.el9.x86_64.rpm

attention : openldap-ltb-2.6.6-1.el9.x86_64.rpm: Entête V4 DSA/SHA1 Signature, clé ID 6d45bfc5: NOKEY
Name        : openldap-ltb
Version     : 2.6.6
Release     : 1.el9
Architecture: x86_64
Install Date: (not installed)
Group       : Applications/System
Size        : 9071654
License     : OpenLDAP Public License
Signature   : DSA/SHA1, mer. 23 août 2023 10:53:56, Key ID 0ac51f926d45bfc5
Source RPM  : openldap-ltb-2.6.6-1.el9.src.rpm
Build Date  : mer. 23 août 2023 10:40:23
Build Host  : kptn-rockylinux9.box.freepro.com
Packager    : Clement OUDOT <clem.oudot@gmail.com>
Vendor      : LTB-project
URL         : http://www.openldap.org/
Summary     : OpenLDAP server with addons from the LDAP Tool Box project
Description :
OpenLDAP is an open source suite of LDAP (Lightweight Directory Access
Protocol) applications and development tools. LDAP is a set of
protocols for accessing directory services (usually phone book style
information, but other information is possible) over the Internet,
similar to the way DNS (Domain Name System) information is propagated
over the Internet.
```

**Comment by coudot** [comment]
I just published EL9 RPMs with a new GPG key that can be found here: https://ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-PROJECT-SECURITY

RPMs can be found here:
https://ltb-project.org/rpm/openldap25/9/x86_64/
https://ltb-project.org/rpm/openldap26/9/x86_64/

@kwizart @xavierba looks good to you?

**Comment by kwizart** [comment]
@coudot 
Thanks, the GPG key looks good, but I don't see any signature applied to the openldap-tlb latest packages from 2.6 or 2.5.

Please remind that you cannot have two signatures applied on the same RPM, so it might be better to use rpmsign --resign *.rpm

Also depending on the system you are using to sign package, you might need to tune the default algo for GPG signature from SHA1 to SHA256
```
cat .gnupg/gpg.conf
cert-digest-algo SHA256
```
---

You should have something like this:
```
rpm -qpi ffmpeg-5.1.4-1.fc37.x86_64.rpm  |grep Signature                                                                                                       
Signature   : RSA/SHA256, mer. 15 nov. 2023 23:21:26, Key ID e06f8ecdd651ff2e
```

**Comment by coudot** [comment]
@kwizart Indeed I did not published to correct packages yesterday evening, this should be fixed now, could you check?

```
$ rpm -qip x86_64/openldap-ltb-2.6.7-1.el9.x86_64.rpm 
warning: x86_64/openldap-ltb-2.6.7-1.el9.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 91ef05e4: NOKEY
Name        : openldap-ltb
Version     : 2.6.7
Release     : 1.el9
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 6096178
License     : OLDAP-2.8
Signature   : RSA/SHA512, Thu 08 Feb 2024 11:04:35 PM CET, Key ID e99f621691ef05e4
Source RPM  : openldap-ltb-2.6.7-1.el9.src.rpm
Build Date  : Tue 06 Feb 2024 03:59:57 PM CET
Build Host  : ltb-ci-rockylinux9-openldap26-ltb-ci-rpmbuild-pod
URL         : https://www.openldap.org/
Summary     : OpenLDAP server with addons from the LDAP Tool Box project
Description :
OpenLDAP is an open source suite of LDAP (Lightweight Directory Access
Protocol) applications and development tools. LDAP is a set of
protocols for accessing directory services (usually phone book style
information, but other information is possible) over the Internet,
similar to the way DNS (Domain Name System) information is propagated
over the Internet.

This package contains all: server, clients, librairies and docs. It
can be installed with openldap and openldap-devel. It provides tools
from the LDAP Tool Box project:
o Start/stop script
o Logrotate script
```

Why this warning?
```
warning: x86_64/openldap-ltb-2.6.7-1.el9.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 91ef05e4: NOKEY
```

**Comment by kwizart** [comment]
> Why this warning?

When does this occurs? Probably the GPG key isn't already imported on the running host ? (rpm --import RPM-GPG-KEY-LTB-PROJECT-SECURITY will do, or will be asked on the first install by yum/dnf).

It looks good for the el9 latest rpm, but the previous one aren't resigned, so they cannot be gpgchecked with the new key.
I think it would be good to resign them in case there is any need to downgrade for any reason. That way the whole el9 repository will be signed with the working new GPG KEY.

For EL8/EL7, I guess they are signed with the older key and mechanism.
It probably worth to keep the existing key until EL7 EOL by June 2024.

But for EL8, it would be good to transition. Maybe both keys can be advertised to be used for EL8 dnf repo

**Comment by coudot** [comment]
Hello @kwizart,

thanks a lot for your feedback, importing the GPG key was indeed the trick to check the signature

I re-signed all EL9 RPMs in the repository, should be ok!

I'll keep old key for EL7/EL8 for this release, but agree to switch for next release.

**Comment by kkeane** [comment]
I just tried it, and can confirm that the RPMs are now working, after adding the new key.

The correct key is https://ltb-project.org/documentation/_static/RPM-GPG-KEY-LTB-PROJECT-SECURITY

Sent with [Proton Mail](https://proton.me/) secure email.
