### ISSUE TITLE
integration for ppm 1.6

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#11]
include ppm 1.6 in OpenLDAP packaging.
Changelog : adding cracklib support

See also https://github.com/ltb-project/openldap-deb/issues/5

**Comment by davidcoutadeur** [comment]
With cracklib feature, ppm is now covering every "ppolicy checkpassword" functionnality... and adds lots of new features in a better way.
Maybe the discussion to replace checkpassword by ppm can be reopened?

**Comment by coudot** [comment]
Why not, I don't know if we need to replace, as both modules are shipped with LTB package. We can of course communicate to say the checkpassword is obsolete and remove it completely in next major version (OpenLDAP 2.5).

I would also like to know if you would accept to transfer the ppm repository inside @ltb-project github space. This would allow to have all sub projects in one place.

**Comment by davidcoutadeur** [comment]
> We can of course communicate to say the checkpassword is obsolete and remove it completely in next major version (OpenLDAP 2.5).

It can be sufficient. The main idea is simplification! I don't think we need to maintain concurrent codes, especially if one haven't been updated for a very long time.

> I would also like to know if you would accept to transfer the ppm repository inside @ltb-project github space. This would allow to have all sub projects in one place.

Of course. I had this in mind too.

**Comment by davidcoutadeur** [comment]
Will be done when this is solved:
"You don’t have the permission to create repositories on ltb-project"

**Comment by coudot** [comment]
Should be ok now

**Comment by coudot** [comment]
Hello @davidcoutadeur, thanks for moving ppm project. I see that you did not tag any 1.6 version for the moment, I would need it to include it in our RPM packages.

**Comment by coudot** [comment]
For information I created an archive with:
` git archive --prefix=ppm-1.6/ -o /home/clement/dists/ppm-1.6.tar.gz master`

**Comment by davidcoutadeur** [comment]
I have just created the 1.6 tag and corresponding release.

**Comment by coudot** [comment]
Thanks. RPM packages are ready now.
