### ISSUE TITLE
Fix rhel (and derrivates) conditionals

### ISSUE THREAD

**Issue by kwizart** [ltb-project/openldap-rpm#110]
Using the RPM "dist" macro to compare versions across "Enterprise" RPM distributions is un-reliable, it's more common to use the %{rhel} macro for this task (that is due to be implemented by any RHEL derivatives) , or the version specific %{?el7} (and alikes) one.

So I would like to change this
`%if "%{?dist}" == ".el8" || "%{?dist}" == ".el9"`

With this equivalent:
`%if 0%{?!el7:1}`

The benefit is when a newer version is due to be introduced, (like RHEL 10 that willl comes as CentOS Stream 10 in the next months, using dist as .el10next), then the check will already be compatible.

If ACK, I can provide a PR for all openldap 24 ,25 and 26(main) branches.

**Comment by xavierba** [comment]
Agreed, minus the typo: `0%{?!el7:1}` should be `0%{!?el7:1}`

**Comment by xavierba** [comment]
Fixed with https://github.com/ltb-project/openldap-rpm/pull/114
