### ISSUE TITLE
Build issue with openssl11 on EL7

### ISSUE THREAD

**Issue by kwizart** [ltb-project/openldap-rpm#111]
I have an issue with the way the openldap25+ packages are built on EL7.

With this older distro, a newer libevent-ltb package is provided, but this last is built with the usual openssl package wheras openldap-ltb package is built with the newer (epel provided) openssl11 one.

While it's possible that symbol version-ing prevent any clash from the two openssl (0.9.8) and openssl11 (1.1.1k) in the openldap running process, it's not very confident method and could run into unexpected/random crash.

I would suggest to build the newer libevent-ltb with openssl11 also. Same as the version used by openldap-ltb.
(PR coming if ACKed).

**Comment by xavierba** [comment]
Agreed, it's probably better to build against openssl11 for EL7, just to be on the safe side rather than rely on symbol versioning.

**Comment by davidcoutadeur** [comment]
Done
