### ISSUE TITLE
Package OpenLDAP-LTB 2.4.45

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#12]
Package OpenLDAP-LTB 2.4.45 for Red-Hat

**Comment by coudot** [comment]
I think I will not produce RHEL 5 packages anymore, as this distribution is only on extended support: https://access.redhat.com/support/policy/updates/errata/#Life_Cycle_Dates

I will release EL6 and EL7 packages.

**Comment by davidcoutadeur** [comment]
Ok for RHEL 5... I am not sure it is really useful to support 32 bit OS version either

**Comment by coudot** [comment]
I kept 32 bits packages for RHEL 6 for this time.

Packages are done and uploaded to server. Let me know when we can publish Debian ones.
