### ISSUE TITLE
Wrong permissions ownership of installed binaries

### ISSUE THREAD

**Issue by stroeder** [ltb-project/openldap-rpm#14]
slapd executable, all libs, all slapd modules, etc. are installed with ownership ldap:ldap. But ldap is the demon user for running slapd. This is very bad security practice.

Only the database directory /usr/local/openldap/var/openldap-data must have ownership ldap:ldap. The rest of all files should be installed with ownership root:root (with same permissions like now).

**Comment by davidcoutadeur** [comment]
You must also add  /usr/local/openldap/var/run to ldap:ldap user, else OpenLDAP will not start

**Comment by coudot** [comment]
Should be ok with latest commit.

Items to check:
* Remove ownership on backup path, requires a change in slapd-cli
* Remove ownership on password policy checker modules, need to test if OpenLDAP can load them as root
