### ISSUE TITLE
Warning when installing source RPMs from https://ltb-project.org/

### ISSUE THREAD

**Issue by arekkusu** [ltb-project/openldap-rpm#16]
No sure if I should report his here as i concern source RPM package from https://ltb-project.org/

* Installed source rpm gives warning as bellow
* rpm does exit successfully and create file in /root/rpmbuild/

Tested on CentOS 7.4

```
[vagrant@localhost tmp]$ wget http://ltb-project.org/archives/openldap-ltb-2.4.45-1.el7.src.rpm
(...)
2018-01-26 13:11:55 (978 KB/s) - ‘openldap-ltb-2.4.45-1.el7.src.rpm’ saved [5697986/5697986]

[vagrant@localhost tmp]$ sudo rpm -Uvh openldap-ltb-2.4.45-1.el7.src.rpm
Updating / installing...
   1:openldap-ltb-2.4.45-1.el7        ################################# [100%]
warning: user clement does not exist - using root
warning: group clement does not exist - using root
warning: user clement does not exist - using root
warning: group clement does not exist - using root
warning: user clement does not exist - using root
warning: group clement does not exist - using root
warning: user clement does not exist - using root
warning: group clement does not exist - using root
warning: user clement does not exist - using root
warning: group clement does not exist - using root
warning: user clement does not exist - using root
warning: group clement does not exist - using root
warning: user clement does not exist - using root
warning: group clement does not exist - using root
warning: user clement does not exist - using root
warning: group clement does not exist - using root
```

**Comment by coudot** [comment]
Does not seems to fail, you just have warnings.

**Comment by arekkusu** [comment]
Sorry, my mistake. Not really familiar with source rpm.

I was reading this and though it would be installed in '/usr/src/rpm'
https://ltb-project.org/documentation/openldap-rpm#yum_repository

I updated the issues. Not sure how significant the warning is. I'll let you decide ;)

**Comment by coudot** [comment]
Is it not installed in /usr/src/rpm? To be honnest, I never use this.

**Comment by arekkusu** [comment]
It got installed in ``/root/rpmbuild/``

**Comment by eseyman** [comment]
The user and group warnings are harmless and can be safely ignored.

These days, source rpms installed on Fedora/Centos hosts install their spec files in $HOME/rpmbuild/SPECS while the source code goes in $HOME/rpmbuild/SOURCES. You can run the commands `rpm --eval "%{_specdir}"` and `rpm --eval "%{_sourcedir}"` to get the exact locations.

As an aside, I would advise not using the root user to install/build source rpms.
