### ISSUE TITLE
Why are OpenLDAP modules compiled in static?

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#24]
Why are OpenLDAP modules compiled in static?

**Comment by coudot** [comment]
It's a choice made a long time ago to ease configuration (no need to load modules). The benefit to have overlays in modules is quite poor.

We use modules for contrib overlays.

**Comment by davidcoutadeur** [comment]
Ok thanks. I don't think there is more to say about this, so I close the issue.
