### ISSUE TITLE
Provide default data and configuration

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-rpm#26]
A good feature would be to provide a default configuration and some sample data so we start with some entries in the directory

**Comment by davidcoutadeur** [comment]
This could be a job for the cli script:

new target testprovisionnew target testconfignew target testprovisionpolicy

This is just a first suggestion, we may need to check other target or target names

**Comment by coudot** [comment]
Done with slapd-cli 1.8

See 9b375eacfa5fcc011e4fe07a3aa20ebe745a3484
