### ISSUE TITLE
Provide all backends and overlays as modules

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-rpm#28]
We choosed to compile official backends and overlays in static mode at the beginning of the project. I recnetly had an issue with this choice : OpenAM is using a specific schema with memberOf in it, which is also redefined in memberOf overlay. With this overlay compiled as static, even if the overlay is not loaded in configuration, the schema is defined and we can't include the OpenAM schema.

So I open this issue so we can discuss to change this mode and provide all backends and overlays as modules.

As this will require a change in configuration (moduleload), I plan it for 2.5.

**Comment by xps2** [comment]
I was having trouble migrating the OpenAM schema to openldap-ltb.
Since the official package of RHEL7 is a module, I want overlay to be a module.

**Comment by coudot** [comment]
Done in 9b375eacfa5fcc011e4fe07a3aa20ebe745a3484
