### ISSUE TITLE
Argon2: Add new algorithm password hashing 

### ISSUE THREAD

**Issue by Meheni** [ltb-project/openldap-rpm#33]
Today, security advise to use the Argon2 hashing algorithm.
SH2 and PBKDF2 are become deprecated and I think Argon2 should be the reference.

**Comment by coudot** [comment]
Is there any code in OpenLDAP source providing this?

**Comment by davidcoutadeur** [comment]
Seems interresting.
The patch provides a complete module we could include in the next distribution.
The module needs one dependency: `libargon2-dev` (debian) / `libargon2-devel` (epel)
For future references:
`ftp://ftp.openldap.org/incoming/simon-levermann-170126.patch`

@Meheni : do you know if OpenLDAP community intends to include it in their future 2.5 release?

**Comment by bitsofinfo** [comment]
Apparently argon2 will be in 2.4.50.... looking forward to it. I assume you guys can get an RPM for that once released?

https://lists.openldap.org/hyperkitty/list/openldap-technical@openldap.org/message/UE7YJIUREL3P5UNAPSKHDIVZCNT4YZJ4/

**Comment by bitsofinfo** [comment]
https://git.openldap.org/openldap/openldap/-/tree/master/contrib/slapd-modules/passwd/argon2
