### ISSUE TITLE
 Fix ppm issue when checkRDN is set

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#38]
Fix this issue: https://github.com/ltb-project/ppm/issues/16

**Comment by coudot** [comment]
@davidcoutadeur we need a release of ppm if we want to include it in new RPMs

**Comment by davidcoutadeur** [comment]
Hi @coudot
Not sure of what you mean.
Do you suggest making a new release of ppm for each new version of openldap-ltb rpm?
What if there is no change in ppm for the new openldap release? Maybe in this case could we keep the old ppm package?

**Comment by coudot** [comment]
No, but in this case, you made a change in ppm code, and you did not release a new version.

With RPM, we rely on a tarball for ppm. For the moment we build with ppm 1.7. I can build with ppm 1.8 to include your fix, but this need to be released.

**Comment by davidcoutadeur** [comment]
@coudot Ok in this case, I prefer investigate and if possible close this issue: ltb-project/ppm#16 before releasing, because there is too few changes for making a ppm release I think.

Note: making a new release of ppm will certainly invalidate the current debian packages, so I will send you an update.

**Comment by davidcoutadeur** [comment]
Original bug fixed in https://github.com/ltb-project/ppm/issues/16
