### ISSUE TITLE
package naming problem for 2.4.48

### ISSUE THREAD

**Issue by phodient** [ltb-project/openldap-rpm#39]
The openldap-ltb-ppm package for 2.4.48 (#36) overwrote the previous existing package, by reusing the exact same name-major-minor as the previous package (ex. **_openldap-ltb-ppm-1.7-1.el7.x86_64_**) but now introduced a dependency on openldap-ltb-2.4.48.

The version number should probably be bumped to **_openldap-ltb-ppm-1.7-2_** so as not to overwrite existing packages.

Probably a build system bug?

**Comment by coudot** [comment]
Hello @phodient 

Usually we don't update ppm and checkpassword versions because there is no change in slapd C API. You should be able to use the old ppm package with the new openldap version.

**Comment by davidcoutadeur** [comment]
@coudot I think it should be solved by issue, isn't it? :
Include new ppm 1.8 release #40

**Comment by coudot** [comment]
Yes, indeed, we will increase the version number

**Comment by phodient** [comment]
I know it seems trivial, but our build pipeline assumes that once a specific package-MAJOR.MINOR-PATCH has been released, it is immutable.

Because you did introduce a very minor change (a changed dependency), I think the common definition of Semantic Versioning (https://en.wikipedia.org/wiki/Software_versioning#Degree_of_compatibility) suggests at least incrementing the patch version to 1.7-2:

`The patch number is incremented for minor changes and bug fixes which do not change the software's application programming interface (API). `

And you are correct - you can use the old ppm package with the new openldap-ltb - but our pipeline assumes immutability, and does not account for newly introduced dependencies. (Our first inclination when we discovered this problem in the pipeline is that someone had introduced malicious code into openldap-ltb-ppm-1.7-1 and surreptitiously published it.)

But the reverse is part of the problem - you cannot use the new ppm package with the old openldap-ltb - and the old ppm package is no longer available because you overwrote it.

**Comment by coudot** [comment]
@phodient ok, so we will update the PATCH version at each release for additional modules (ppm, check_password, explockout)
