### ISSUE TITLE
Apply patches for ITS 9146 and ITS 9150

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-rpm#48]
The bug  9146 (http://www.openldap.org/its/index.cgi/Software%20Bugs?id=9146) affects Amazon Linux and downgrade replication performances.

The bug 9150 (http://www.openldap.org/its/index.cgi/Software%20Bugs?id=9150) affects all distributions and impact people using slaptest to convert configuration from slapd.conf to cn=config and using MDB backend. The fix will restore database consistency but can impact write performances.

**Comment by davidcoutadeur** [comment]
Both fixes are already included in openldap-2.4.49, which will be released soon. (testing call sent 13th of january) Maybe could we just wait for this release?

**Comment by coudot** [comment]
No I will release this special version this week. No impact for Debian packages, we will indeed wait for 2.4.49 for them.

**Comment by davidcoutadeur** [comment]
Ok.
For info, if I have enough time, I may release a new version of ppm for 2.4.49 version. I'll keep you informed.
