### ISSUE TITLE
Provide more detailed documentation

### ISSUE THREAD

**Issue by UweSauter** [ltb-project/openldap-rpm#51]
Due to Red Hat not supporting OpenLDAP on RHEL8/CentOS8 I'm currently evaluating LTB.
What makes it kind of hard is the missing documentation regarding service configuration. I'm not talking about the configuration of the LDAP directory in `slapd.conf`/`slapd.d` but the configuration of the service startup.

On RHEL/CentOS < 8 there was `/etc/sysconfig/slapd` where it was possible to configure the URLs and thus the IP addresses and protocols the slapd instance should bind to. This was referenced in the `slapd.service` systemd unit file.
Being in a separate file this was persistent across package updates.
E.g. `/etc/sysconfig/slapd`:
```
SLAPD_URLS="ldapi:/// ldap://localhost/ ldaps:///"
SLAPD_OPTIONS="-f /etc/openldap/slapd.conf"
```
and relevant part of `/usr/lib/systemd/system/slapd.service`:
```
[Service]
Type=forking
PIDFile=/var/run/openldap/slapd.pid
Environment="SLAPD_URLS=ldap:/// ldapi:///" "SLAPD_OPTIONS="
EnvironmentFile=/etc/sysconfig/slapd
ExecStartPre=/usr/libexec/openldap/check-config.sh
ExecStart=/usr/sbin/slapd -u ldap -h ${SLAPD_URLS} $SLAPD_OPTIONS
```
This configuration would instruct slapd to bind to port 389 on the loopback interface, allowing only local connections to this unencrypted port, as well as opening a Unix socket and listening on all interfaces on port 636. Also, the old `slapd.conf` file should be used instead of the `slapd.d` directory.

What I have found so far while tooking at the LTB package is that this kind of service configuration seems to be handled inside `/usr/local/openldap/sbin/slapd-cli`.
Is this correct? Is this update persistent? What other way exists to configure the startup behavior of slapd?

I'd appreciate if documentation could be added (on https://ltb-project.org) that explains the difference  between distribution-provided packages and LTB packages, both in configuration and in installation destination.

**Comment by coudot** [comment]
You are right, we can do better.

You can find the documentation about service configuration here: https://ltb-project.org/documentation/openldap-initscript

**Comment by UweSauter** [comment]
Thanks, that helps a lot.

Do I understand that page correctly that I need to create `/usr/local/openldap/etc/openldap/slapd-cli.conf` in order to override the defaults provided in the startup script?
If so, do I need to define all mandatory variables or only those I want changed? I think, the provided defaults will be overridden at the time the configuration file is sourced but I'd like to ensure I understand correctly.

**Comment by coudot** [comment]
You should not create this file, it should be installed by the package.

It is tagged as a configuration file, so it won't be erased by package updates.

**Comment by UweSauter** [comment]
Ah, yes, you are right. Thanks again.

**Comment by coudot** [comment]
Note that a new documentation version is now in https://github.com/ltb-project/documentation
