### ISSUE TITLE
Remove lastbind overlay in OpenLDAP 2.5

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#52]
It seems that lastbind overlay will be included nativally into OpenLDAP 2.5. (see for example: https://bugs.openldap.org/show_bug.cgi?id=9156)

If it is true, we will have to remove lastbind overlay, and warn users that configuration directives have changed (overlay lastbind -> lastbind on)

**Comment by coudot** [comment]
As we discussed, we keep lastbind for 2.5

**Comment by davidcoutadeur** [comment]
Agreed and close. See #83 for OpenLDAP 2.6 release
