### ISSUE TITLE
Release 2.4.52 packages

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-rpm#59]

**Comment by davidcoutadeur** [comment]
I don't know if you are in a hurry, but if not, we could release a new version of ppm, included in openldap-ltb-2.4.52.
The new ppm version would include: https://github.com/ltb-project/ppm/issues/27

**Comment by coudot** [comment]
I just saw the issue, so yes, we can wait for a new ppm release

**Comment by coudot** [comment]
Hello @davidcoutadeur, any idea when you will have time to release a new version of ppm?

**Comment by davidcoutadeur** [comment]
Hello @coudot, I am trying to start this issue this week, but I will probably finish this week-end. This week-end I will also build the 2.4.52 version of OpenLDAP-LTB.

**Comment by coudot** [comment]
Looking at ltb-project/ppm#27, I understand we keep the current ppm version for 2.4.52.

I am working on RPM packages

**Comment by coudot** [comment]
I confirm we have the SSL issue for CentOS 6:
```
gcc -DOPENLDAP_FD_SETSIZE=4096 -O2 -g -DSLAP_SCHEMA_EXPOSE -o apitest apitest.o  -L/usr/local/berkeleydb/lib ./.libs/libldap.a /home/clement/build/BUILD/openldap-2.4.52/libraries/liblber/.libs/liblber.a ../../libraries/liblber/.libs/liblber.a ../../libraries/liblutil/liblutil.a -lsasl2 -lssl -lcrypto -lcrypt -lresolv
./.libs/libldap.a(os-ip.o): In function `ldap_pvt_is_socket_ready':
/home/clement/build/BUILD/openldap-2.4.52/libraries/libldap/os-ip.c:262: warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead
/home/clement/build/BUILD/openldap-2.4.52/libraries/libldap/os-ip.c:262: warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead
./.libs/libldap.a(tls_o.o): In function `tlso_ctx_init':
/home/clement/build/BUILD/openldap-2.4.52/libraries/libldap/tls_o.c:416: undefined reference to `SSL_CTX_set1_curves_list'
/home/clement/build/BUILD/openldap-2.4.52/libraries/libldap/tls_o.c:428: undefined reference to `SSL_CTX_set_ecdh_auto'
collect2: ld returned 1 exit status
make[2]: *** [apitest] Error 1
make[2]: Leaving directory `/home/clement/build/BUILD/openldap-2.4.52/libraries/libldap'
make[1]: *** [all-common] Error 1
make[1]: Leaving directory `/home/clement/build/BUILD/openldap-2.4.52/libraries'
make: *** [all-common] Error 1
erreur: Mauvais status de sortie pour /var/tmp/rpm-tmp.XZ44bl (%build)

**Comment by davidcoutadeur** [comment]
Yes, no update for ppm.
I am waiting for an optional response from the author of the pull request to reevaluate it, but by default I am going to reject it if there is no answer soon.

Noted for ContOS 6. I hope at least CentOS 7 is going to work though.

**Comment by coudot** [comment]
Yes, CentOS7 and CentOS8 packages will be available.
