### ISSUE TITLE
integrate new 1.5 release of ppm

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#7]
See https://github.com/davidcoutadeur/ppm/releases/tag/v1.5

By the same time, it would be good to distinguish the files from ppm / files from original OpenLDAP.
ppm added files are:
- ppm.so (in lib directory)
- ppm_test (in lib directory)
- ppm.conf (in etc/openldap directory)

**Comment by coudot** [comment]
Hi @davidcoutadeur, I included ppm v1.5 in  commit 36ca60d, but I have an issue when running ppm_test:
```
[root@centos7 lib64]# ./ppm_test 
./ppm_test: error while loading shared libraries: ppm.so: cannot open shared object file: No such file or directory
```

Of course adding /usr/local/openldap/lib64 in /etc/ld.so.conf would resolve the problem but add conflicts between system LDAP libs and LTB LDAP libs. Did you found a solution in Debian packaging?

**Comment by davidcoutadeur** [comment]
Yep, I didn't want either to add the library to the system ones.
You can see the solution in the unit test script, which by the way is launched during compilation.
https://github.com/ltb-project/openldap-deb/blob/master/debian/paquet-openldap-debian/openldap-ltb-2.4.44/ltb-project-openldap-ppm-1.5/unit_tests.sh

`
PPM_CONFIG_FILE="${CONF}" LD_LIBRARY_PATH="${LIB_PATH}" ./ppm_test "${PASS}"
`

**Comment by coudot** [comment]
Great, in this case there is nothing more to do in the packaging.

Thanks for the answer.
