### ISSUE TITLE
create a different service name

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#73]
The new major version of OpenLDAP is an opportunity to choose a new name for OpenLDAP service name.

Maybe `slapd-ltb`?

Maybe we could also change the default port from 389 to 3389, for having slapd and slapd-ltb live together? (this has to be discussed, it might not be the best idea)

**Comment by coudot** [comment]
Ok for `slapd-ltb`

But we should keep 389 as default port

**Comment by coudot** [comment]
Done in 9b375eacfa5fcc011e4fe07a3aa20ebe745a3484
