### ISSUE TITLE
review list of modules in contrib-overlays for new major version of OpenLDAP

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#77]
The list of modules must be reviewed:
- some must be added / replaced / removed

**Comment by coudot** [comment]
See 9b375eacfa5fcc011e4fe07a3aa20ebe745a3484

TODO:
* Add new overlays (see selection from Debian packages)

**Comment by davidcoutadeur** [comment]
all overlays are now correctly compiled and dispatched into main openldap and contrib packages.

See 007e050
