### ISSUE TITLE
use ppm newly included in contrib

### ISSUE THREAD

**Issue by davidcoutadeur** [ltb-project/openldap-rpm#78]
ppm is now included into OpenLDAP contrib since 2.5.3 beta

There is integration work to do again, especially Makefile has big modifications (many variable names have changed)

**Comment by coudot** [comment]
See 9b375eacfa5fcc011e4fe07a3aa20ebe745a3484

TODO:
* Man page (included in OpenLDAP 2.5.8)
* Convert old ppm.conf config?

**Comment by davidcoutadeur** [comment]
> Convert old ppm.conf config?

Not really usefull... Nothing has really changed.

And it is hard to guess in which policy entry to migrate the configuration...

Also a bad pwdCheckModuleArg can lead to a slapd crash. It is really import to have a manual admin review of the ppm configuration

**Comment by davidcoutadeur** [comment]
man page is included conditionally wether the release is =2.5.7 or not.

seems everything is ok, I close this issue.
