### ISSUE TITLE
Clustering and network dependencies

### ISSUE THREAD

**Issue by ggambini** [ltb-project/openldap-rpm#79]
Hello

We have a multi master cluster with 3 nodes. slapd.conf file is exactly same on each node, each 3 providers is defined like this :
```
serverID        1       ldaps://node1:636
serverID        2       ldaps://node2:636
serverID        3       ldaps://node3:636
[...]
syncrepl        rid=1
                    provider=ldaps://node1:636
                    [...]

syncrepl        rid=2
                    provider=ldaps://node2:636
                    [...]

syncrepl        rid=3
                    provider=ldaps://node3:636
                    [...]
```

Each node know is name a start with slapd-cli.conf and SSLIP variable :
```
SSLIP="node1"
SLAPD_SERVICES="ldaps://$SSLIP:$SSLPORT ldapi://$LDAPI_SOCKETURL"
```

Its work very well with automatic deployment. There is a limitation, at server boot, if network not ready, slapd cant find interface targeted in SSLIP variable. We need to patch /usr/lib/systemd/system/slapd.service and modify "After" directive like this : 
```
After=syslog.target network.target NetworkManager-wait-online.service
```

Can you add NetworkManager-wait-online.service in systemd template file ? Or, did you know a workaroud ?
Regards, Gilian.

**Comment by faust64** [comment]
I would say the NetworkManager-wait-online dependency is implicit - if NetworkManager is enabled.
The network.target mentioned in the `After` of the slapd unit sounds good already.

On a debian 10:

```
$ cat /lib/systemd/system/NetworkManager-wait-online.service
[Unit]
Description=Network Manager Wait Online
Documentation=man:nm-online(1)
Requisite=NetworkManager.service
After=NetworkManager.service
Before=network-online.target
[...]
```

Or a CentOS 8:

```
# cat /usr/lib/systemd/system/NetworkManager-wait-online.service
[Unit]
Description=Network Manager Wait Online
Documentation=man:nm-online(1)
Requires=NetworkManager.service
After=NetworkManager.service
Before=network-online.target
[...]
```

Can you check your NetworkManager-wait-online unit definition? Don't you have something like this?

**Comment by ggambini** [comment]
Hello

Im on RHEL8 and NetworkManager-wait-online.service file is vanilla. To be honest, i dont really understand how network-manager work. I think network.target just start network but don't check if up. network-online.target seem do nothing only wait NetworkManager-wait-online.service, it act like an alias ?

slapd with our configuration, need to know his IP address. He is started just after network.target but interfaces isn't up and dont already have an IP address ? Our server have static IPv4 configuration but network layer maybe slow.

Regardes, Gilian.

My NetworkManager-wait-online :
```
#cat /usr/lib/systemd/system/NetworkManager-wait-online.service
[Unit]
Description=Network Manager Wait Online
Documentation=man:nm-online(1)
Requires=NetworkManager.service
After=NetworkManager.service
Before=network-online.target

[Service]
# `nm-online -s` waits until the point when NetworkManager logs
# "startup complete". That is when startup actions are settled and
# devices and profiles reached a conclusive activated or deactivated
# state. It depends on which profiles are configured to autoconnect and
# also depends on profile settings like ipv4.may-fail/ipv6.may-fail,
# which affect when a profile is considered fully activated.
# Check NetworkManager logs to find out why wait-online takes a certain
# time.

Type=oneshot
ExecStart=/usr/bin/nm-online -s -q
RemainAfterExit=yes

# Set $NM_ONLINE_TIMEOUT variable for timeout in seconds.
# Edit with `systemctl edit NetworkManager-wait-online`.
#
# Note, this timeout should commonly not be reached. If your boot
# gets delayed too long, then the solution is usually not to decrease
# the timeout, but to fix your setup so that the connected state
# gets reached earlier.
Environment=NM_ONLINE_TIMEOUT=30

[Install]
WantedBy=network-online.target
```

**Comment by ggambini** [comment]
Hello @coudot 

I have a question about 2.5 upgrade on EL8. LTB 2.5 rpms require openldap.x86_64 from official Red Hat baseos-rpms repository. Red Hat remove openldap in future version, for EL8 where i can find openldap 2.5 rpm ? baseos-rpms repo seems dont provide it. (you have a local RH network satelite, maybe missing something on it ?)

About issue's problem, we have a fix. We dont edit your systemd file, he is include in /etc/systemd/system/slapd.service and we had our custom :
```
.include /usr/lib/systemd/system/slapd.service
[Unit]
After=NetworkManager-wait-online.service
```

Regards, Gilian.

**Comment by coudot** [comment]
We don't require openldap from official RHEL repository

You can install LTB RPMs directly on RHEL8, we provide the needed systemd files.

Please remove old OpenLDAP packages, you may have some conflicts

**Comment by ggambini** [comment]
Hello

My bad, openldap-ltb or openldap-ltb-contrib-overlays dont have requirement with openldap, sorry. (next time, i will check with dnf before ask :)
Have you try a multimaster cluster with 2.4 and 2.5 nodes ? Or its a bad idea and we need to update all nodes at same time (with a service down time ?)
We can test a "rolling update like" on a non-prod cluster.

Thank you, Gilian.

**Comment by coudot** [comment]
OpenLDAP developers do not guarantee replication compatibility between 2.4 and 2.5.

You can read their new release policy here: https://lists.openldap.org/hyperkitty/list/openldap-announce@openldap.org/thread/2QQNVWPUUG54JM7FGQHMMF3H4KS2PPKQ/
