### ISSUE TITLE
check_password.so not found

### ISSUE THREAD

**Issue by agriffit79** [ltb-project/openldap-rpm#86]
Deployed openldap-ltb-2.4.59-1 and openldap-ltb-check-password-1.1-20 on CentOS 7.9.

When attempting to change a password the quality check fails with

`check_password_quality: lt_dlopen failed: (check_password.so) file not found.`

The only way I could find to get this work was to add a systemd drop-in to populate LD_LIBRARY_PATH

> [Service]
> Environment=LD_LIBRARY_PATH=/usr/local/openldap/lib64

Is this a known issue, or something weird about my setup?

**Comment by davidcoutadeur** [comment]
Hello,

You should provide your slapd configuration + password policy content for allowing us to analyze your problem.

I suspect you didn't set the full path:
```
pwdCheckModule: /usr/local/openldap/lib64/check_password.so
```

**Comment by davidcoutadeur** [comment]
Moreover, please use the mailing list rather than opening an issue if you have a question.

**Comment by agriffit79** [comment]
Yes, that was the issue. Thanks.

(I'll use the mailing list in future)
