### ISSUE TITLE
Repo Mirroring Issue

### ISSUE THREAD

**Issue by logdou** [ltb-project/openldap-rpm#89]
Receiving the following error message when attempting to mirro repo locally on our network:

Treeinfo file should have INI format

**Comment by logdou** [comment]
Correct, Satellite 6.10.2 (upstream product The Foreman 2.5.2.18-3).  URL being specified is https://ltb-project.org/rpm/8Server/x86_64/

No further useful info on the error in the logs other than a Satellite-specific stack trace upon failure.

**Comment by coudot** [comment]
This is an issue with our ErrorDocument directive, which redirects when a file is not found. We need to find the correct configuration on our side to disable ErrorDocument for rpm/ subdirectory.

**Comment by coudot** [comment]
I changed the ErrorDocument configuration, is this working better?

**Comment by maschmutz** [comment]
> I changed the ErrorDocument configuration, is this working better?

For me it works fine now. Thank you for your responsiveness on Libera Chat. 👌
