### ISSUE TITLE
Segmentation fault in slapd-cli on Rocky Linux 8

### ISSUE THREAD

**Issue by AaronBennett** [ltb-project/openldap-rpm#90]
I've got a new openldlap-ltb 2.5 system (running on rocky 8), and when I try to start it with  "slapd-cli start", it dumps core:

```
[root@kt-ldap-01 slapd.d]$ journalctl -xe Mar 28 16:13:06 kt-ldap-01 systemd-coredump[54716]: Resource limits disable core dumping for process 54714 (slapd).
Mar 28 16:13:06 kt-ldap-01 systemd-coredump[54716]: Process 54714 (slapd) of user 0 dumped core.
-- Subject: Process 54714 (slapd) dumped core
-- Defined-By: systemd

-- Documentation: man:core(5)
--
-- Process 54714 (slapd) crashed and dumped core.
--
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
Mar 28 16:13:06 kt-ldap-01 slapd-cli[54688]: /usr/local/openldap/sbin/slapd-cli: line 350: 54714 Segmentation fault      (core dumped) $SLA>
Mar 28 16:13:06 kt-ldap-01 systemd[1]: [systemd-coredump@13-54715-0.service](mailto:systemd-coredump@13-54715-0.service): Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd


```
From debugging the shell script it looks like it's running slapd with these arguments:
```SLAPD_PARAMS='-h ldaps://{server_fqdn} -F /usr/local/openldap/etc/openldap/slapd.d -u ldap -g ldap -l local4'```

But if I run: 

```/usr/local/openldap/libexec/slapd -h ldaps://{server_fqdn} -F /usr/local/openldap/etc/openldap/slapd.d -u ldap -g ldap -l local4```

It works fine -- starts up with no issues at all.

**Comment by AaronBennett** [comment]
No - haven't looked at it in a while.

From: davidcoutadeur ***@***.***>
Sent: Friday, May 13, 2022 11:33 AM
To: ltb-project/openldap-rpm ***@***.***>
Cc: Aaron Bennett ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [ltb-project/openldap-rpm] Segmentation fault in slapd-cli on Rocky Linux 8 (Issue #90)


@AaronBennett<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAaronBennett&data=05%7C01%7Cabennett%40clarku.edu%7Cea53532f9b4b4778f17908da34f5d883%7Cb5b2263d68aa453eb972aa1421410f80%7C0%7C0%7C637880527766156993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3YnE%2BLDoseKqiRKo9V%2BQvM5gArzjARkHBKvSJPW8MrI%3D&reserved=0> do you have some new elements about this OpenLDAP crash?

-

**Comment by coudot** [comment]
Hello @davidcoutadeur do we know if this issue is fixed by your commit?

**Comment by davidcoutadeur** [comment]
Issue mentioned in commits b7df5c1 and 6529c85 are a mistake. (copy/paste from ltb-project/openldap-deb repository)

They should be linked to: use new ppm 2.2 version #92 

The current issue: "Segmentation fault in slapd-cli on Rocky Linux 8" is linked to a problem with openldap launch, but without any new element, I can't analyse further. @AaronBennett if you don't have any new info to share, I propose to close this issue.
