### ISSUE TITLE
Packages for Entreprise Linux 9

### ISSUE THREAD

**Issue by coudot** [ltb-project/openldap-rpm#99]
We need to work on .el9 packages

I will use Rocky Linux to build them.

**Comment by coudot** [comment]
All dependencies seems ok except for `pandoc` which was in PowerTools in CentOS8 / RockyLinux8 but is not present anymore in any repositories.

`pandoc` is only needed to build ppm man page.

**Comment by davidcoutadeur** [comment]
we could remove pandoc requirement if we rely on a previously generated man page.

Beware pandoc is currently used to build the doc during compilation.

**Comment by coudot** [comment]
Seems pandoc is now available: https://rhel.pkgs.org/9/epel-x86_64/pandoc-2.14.0.3-16.el9.x86_64.rpm.html
